# -*- coding: utf-8 -*-
"""EPOCH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jw0xECWN4Y5nmT2mDWMHJnQkBXcQPVa
"""

!pip install -q librosa==0.10.2 openai-whisper tensorflow scikit-learn matplotlib seaborn
!pip install -q soundfile

import zipfile, os, re, json
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

np.random.seed(42)
tf.random.set_seed(42)

with zipfile.ZipFile('/content/ravdess_audio.zip', 'r') as z:
    z.extractall('/content/ravdess')

EMOTION_MAP = {1:'neutral', 2:'calm', 3:'happy', 4:'sad',
               5:'angry', 6:'fearful', 7:'disgust', 8:'surprised'}
NUM_CLASSES = 8

import glob

def get_label_from_filename(filepath):
    fname = os.path.basename(filepath)
    parts = fname.split('-')
    return int(parts[2]) - 1

audio_files = glob.glob('/content/ravdess/**/*.wav', recursive=True)
labels = [get_label_from_filename(f) for f in audio_files]

print(f"Total files: {len(audio_files)}")
print(f"Label distribution: { {EMOTION_MAP[l+1]: labels.count(l) for l in set(labels)} }")

import glob

def get_label_from_filename(filepath):
    fname = os.path.basename(filepath)
    parts = fname.split('-')
    return int(parts[2]) - 1

def extract_melspectrogram(filepath, sr=22050, n_mels=128, max_len=128,
                           augment=False):
    try:
        y, sr = librosa.load(filepath, sr=sr, duration=3.0)
        target_len = sr * 3
        if len(y) < target_len:
            y = np.pad(y, (0, target_len - len(y)))
        else:
            y = y[:target_len]

        if augment:
            if np.random.rand() < 0.5:
                rate = np.random.uniform(0.85, 1.15)
                y = librosa.effects.time_stretch(y, rate=rate)
            if np.random.rand() < 0.5:
                steps = np.random.randint(-3, 4)
                y = librosa.effects.pitch_shift(y, sr=sr, n_steps=steps)
            if np.random.rand() < 0.3:
                y = y + 0.005 * np.random.randn(len(y))

        if len(y) < target_len:
            y = np.pad(y, (0, target_len - len(y)))
        else:
            y = y[:target_len]

        mel = librosa.feature.melspectrogram(
            y=y, sr=sr, n_mels=n_mels, n_fft=2048, hop_length=512
        )
        mel_db = librosa.power_to_db(mel, ref=np.max)
        mel_db = mel_db[:, :max_len]
        if mel_db.shape[1] < max_len:
            mel_db = np.pad(mel_db, ((0, 0), (0, max_len - mel_db.shape[1])))
        return mel_db
    except Exception as e:
        print(f'Error with {filepath}: {e}')
        return None

audio_files = glob.glob('/content/ravdess/**/*.wav', recursive=True)
labels = [get_label_from_filename(f) for f in audio_files]

print(f'Total files: {len(audio_files)}')
print(f"Label distribution: { {EMOTION_MAP[l+1]: labels.count(l) for l in set(labels)} }")

spectrograms, valid_files, valid_labels = [], [], []

for fpath, label in zip(audio_files, labels):
    mel = extract_melspectrogram(fpath)
    if mel is not None:
        spectrograms.append(mel)
        valid_files.append(fpath)
        valid_labels.append(label)
        mel_aug = extract_melspectrogram(fpath, augment=True)
        if mel_aug is not None:
            spectrograms.append(mel_aug)
            valid_files.append(fpath)
            valid_labels.append(label)

X_audio = np.array(spectrograms)[..., np.newaxis]
y = np.array(valid_labels)

mean = X_audio.mean(axis=(1, 2, 3), keepdims=True)
std  = X_audio.std(axis=(1, 2, 3), keepdims=True)
X_audio = (X_audio - mean) / (std + 1e-8)

print(f'Spectrogram shape: {X_audio.shape}')
print(f'Label shape: {y.shape}')

plt.figure(figsize=(8, 4))
librosa.display.specshow(spectrograms[0], x_axis='time', y_axis='mel')
plt.colorbar(format='%+2.0f dB')
plt.title(f"Emotion: {EMOTION_MAP[y[0]+1]}")
plt.tight_layout()
plt.show()

import whisper

model_whisper = whisper.load_model('base')

transcripts = []

for i, fpath in enumerate(valid_files):
    try:
        result = model_whisper.transcribe(fpath, language='en')
        transcripts.append(result['text'].strip().lower())
    except Exception as e:
        print(f'  Transcription failed for {fpath}: {e}')
        transcripts.append('')

with open('/content/transcripts.json', 'w') as f:
    json.dump(transcripts, f)

import json
with open('/content/transcripts.json', 'r') as f:
    transcripts = json.load(f)

with open('/content/transcripts.json', 'r') as f:
    transcripts = json.load(f)

MAX_WORDS = 5000
MAX_SEQ_LEN = 40

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token='<OOV>')
tokenizer.fit_on_texts(transcripts)
sequences = tokenizer.texts_to_sequences(transcripts)
X_text = pad_sequences(sequences, maxlen=MAX_SEQ_LEN, padding='post', truncating='post')

assert len(X_text) == len(X_audio), (
    f'Mismatch: {len(X_text)} transcripts vs {len(X_audio)} spectrograms'
)

print(f'Text array shape: {X_text.shape}')
print(f'Vocab size used: {min(MAX_WORDS, len(tokenizer.word_index)+1)}')

X_a_train, X_a_test, X_t_train, X_t_test, y_train, y_test = train_test_split(
    X_audio, X_text, y, test_size=0.15, random_state=42, stratify=y
)

X_a_train, X_a_val, X_t_train, X_t_val, y_train, y_val = train_test_split(
    X_a_train, X_t_train, y_train, test_size=0.15, random_state=42, stratify=y_train
)

class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weight_dict = dict(enumerate(class_weights))

print(f'Train: {len(y_train)}, Val: {len(y_val)}, Test: {len(y_test)}')
print('Class weights:', {EMOTION_MAP[k+1]: round(v, 2) for k, v in class_weight_dict.items()})

def build_audio_cnn(input_shape=(128, 128, 1), num_classes=8):
    inp = layers.Input(shape=input_shape)

    x = layers.Conv2D(32, (3, 3), padding='same', use_bias=False)(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Conv2D(32, (3, 3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Dropout(0.2)(x)

    x = layers.Conv2D(64, (3, 3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Conv2D(64, (3, 3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Dropout(0.25)(x)

    x = layers.Conv2D(128, (3, 3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Conv2D(128, (3, 3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Dropout(0.3)(x)

    avg_pool = layers.GlobalAveragePooling2D()(x)
    max_pool = layers.GlobalMaxPooling2D()(x)
    x = layers.Concatenate()([avg_pool, max_pool])

    x = layers.Dense(256, activation='relu',
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.4)(x)
    features = layers.Dense(128, activation='relu',
                            kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.3)(features)
    out = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inp, out, name='audio_cnn')
    return model, features

audio_model, audio_features = build_audio_cnn()

audio_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)
audio_model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

callbacks_audio = [
    EarlyStopping(patience=10, restore_best_weights=True, verbose=1,
                  monitor='val_accuracy'),
    ReduceLROnPlateau(patience=5, factor=0.5, min_lr=1e-6, verbose=1),
    ModelCheckpoint('/content/best_audio.keras', save_best_only=True,
                    monitor='val_accuracy', verbose=0)
]

history_audio = audio_model.fit(
    X_a_train, y_train,
    validation_data=(X_a_val, y_val),
    epochs=60,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=callbacks_audio
)

audio_model.load_weights('/content/best_audio.keras')
audio_test_loss, audio_test_acc = audio_model.evaluate(X_a_test, y_test, verbose=0)
print(f'\nAudio-only Test Accuracy: {audio_test_acc:.4f}')

def build_text_rnn(vocab_size=5000, embed_dim=128, max_len=40, num_classes=8):
    inp = layers.Input(shape=(max_len,))

    x = layers.Embedding(vocab_size, embed_dim, mask_zero=True)(inp)
    x = layers.SpatialDropout1D(0.3)(x)

    x = layers.Bidirectional(layers.GRU(128, return_sequences=True,
                             dropout=0.2, recurrent_dropout=0.2))(x)
    x = layers.Bidirectional(layers.GRU(64, return_sequences=True,
                             dropout=0.2, recurrent_dropout=0.2))(x)
    x = layers.Bidirectional(layers.GRU(32, return_sequences=False,
                             dropout=0.2))(x)

    x = layers.Dense(128, activation='relu',
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.4)(x)
    features = layers.Dense(64, activation='relu',
                            kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.3)(features)
    out = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inp, out, name='text_rnn')
    return model, features

text_model, text_features = build_text_rnn()
text_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
text_model.summary()

callbacks_text = [
    EarlyStopping(patience=10, restore_best_weights=True, verbose=1,
                  monitor='val_accuracy'),
    ReduceLROnPlateau(patience=5, factor=0.5, min_lr=1e-6, verbose=1),
    ModelCheckpoint('/content/best_text.keras', save_best_only=True,
                    monitor='val_accuracy', verbose=0)
]

history_text = text_model.fit(
    X_t_train, y_train,
    validation_data=(X_t_val, y_val),
    epochs=60,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=callbacks_text
)

text_model.load_weights('/content/best_text.keras')
text_test_loss, text_test_acc = text_model.evaluate(X_t_test, y_test, verbose=0)
print(f'\nText-only Test Accuracy: {text_test_acc:.4f}')

def build_fusion_model_safe(num_classes=8):


    a_inp = layers.Input(shape=(128, 128, 1), name='audio_input')
    x = layers.Conv2D(32, (3,3), padding='same', use_bias=False)(a_inp)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.Conv2D(32, (3,3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2,2))(x); x = layers.Dropout(0.2)(x)

    x = layers.Conv2D(64, (3,3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.Conv2D(64, (3,3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2,2))(x); x = layers.Dropout(0.25)(x)

    x = layers.Conv2D(128, (3,3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.Conv2D(128, (3,3), padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x); x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D((2,2))(x); x = layers.Dropout(0.3)(x)

    avg_p = layers.GlobalAveragePooling2D()(x)
    max_p = layers.GlobalMaxPooling2D()(x)
    x = layers.Concatenate()([avg_p, max_p])
    x = layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.4)(x)
    audio_feat = layers.Dense(128, activation='relu', name='audio_bottleneck',
                              kernel_regularizer=regularizers.l2(1e-4))(x)

    t_inp = layers.Input(shape=(40,), name='text_input')
    tx = layers.Embedding(5000, 128, mask_zero=True)(t_inp)
    tx = layers.SpatialDropout1D(0.3)(tx)
    tx = layers.Bidirectional(layers.GRU(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))(tx)
    tx = layers.Bidirectional(layers.GRU(64, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))(tx)
    tx = layers.Bidirectional(layers.GRU(32, return_sequences=False, dropout=0.2))(tx)
    tx = layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(tx)
    tx = layers.Dropout(0.4)(tx)
    text_feat = layers.Dense(64, activation='relu', name='text_bottleneck',
                             kernel_regularizer=regularizers.l2(1e-4))(tx)

    combined = layers.Concatenate()([audio_feat, text_feat])
    fx = layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(combined)
    fx = layers.Dropout(0.4)(fx)
    fx = layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(fx)
    fx = layers.Dropout(0.3)(fx)
    out = layers.Dense(num_classes, activation='softmax')(fx)

    model = models.Model(inputs=[a_inp, t_inp], outputs=out, name='fusion_model')
    return model

fusion_model = build_fusion_model_safe()

for layer in fusion_model.layers:
    if layer.name in audio_layer_names:
        try:
            layer.set_weights(audio_layer_names[layer.name].get_weights())
            transferred_a += 1
        except:
            pass
    elif layer.name in text_layer_names:
        try:
            layer.set_weights(text_layer_names[layer.name].get_weights())
            transferred_t += 1
        except:
            pass

for layer in fusion_model.layers:
    if layer.name not in ('audio_bottleneck', 'text_bottleneck') and \
       not layer.name.startswith('dense') and \
       not layer.name.startswith('dropout') and \
       not layer.name.startswith('concatenate'):
        layer.trainable = False

fusion_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
fusion_model.summary()

callbacks_fusion_phase1 = [
    EarlyStopping(patience=7, restore_best_weights=True, verbose=1, monitor='val_accuracy'),
    ReduceLROnPlateau(patience=3, factor=0.5, min_lr=1e-6, verbose=1),
    ModelCheckpoint('/content/best_fusion.keras', save_best_only=True,
                    monitor='val_accuracy', verbose=0)
]

history_fusion_p1 = fusion_model.fit(
    [X_a_train, X_t_train], y_train,
    validation_data=([X_a_val, X_t_val], y_val),
    epochs=20,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=callbacks_fusion_phase1
)

for layer in fusion_model.layers:
    layer.trainable = True

fusion_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_fusion_phase2 = [
    EarlyStopping(patience=10, restore_best_weights=True, verbose=1, monitor='val_accuracy'),
    ReduceLROnPlateau(patience=5, factor=0.5, min_lr=1e-7, verbose=1),
    ModelCheckpoint('/content/best_fusion.keras', save_best_only=True,
                    monitor='val_accuracy', verbose=0)
]

history_fusion_p2 = fusion_model.fit(
    [X_a_train, X_t_train], y_train,
    validation_data=([X_a_val, X_t_val], y_val),
    epochs=40,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=callbacks_fusion_phase2
)

fusion_model.load_weights('/content/best_fusion.keras')
fusion_test_loss, fusion_test_acc = fusion_model.evaluate([X_a_test, X_t_test], y_test, verbose=0)
print(f'\nFusion (Early) Test Accuracy: {fusion_test_acc:.4f}')

audio_probs = audio_model.predict(X_a_test)
text_probs  = text_model.predict(X_t_test)

avg_probs      = (audio_probs + text_probs) / 2
avg_preds      = np.argmax(avg_probs, axis=1)
avg_acc        = np.mean(avg_preds == y_test)

weighted_probs = 0.7 * audio_probs + 0.3 * text_probs
weighted_preds = np.argmax(weighted_probs, axis=1)
weighted_acc   = np.mean(weighted_preds == y_test)

max_preds = np.where(
    np.max(audio_probs, axis=1) > np.max(text_probs, axis=1),
    np.argmax(audio_probs, axis=1),
    np.argmax(text_probs, axis=1)
)
max_acc = np.mean(max_preds == y_test)

print(f'Late Fusion - Average:            {avg_acc:.4f}')
print(f'Late Fusion - Weighted (0.7/0.3): {weighted_acc:.4f}')
print(f'Late Fusion - Max confidence:     {max_acc:.4f}')

print('\n' + '='*58)
print(f"{'Model':<38} {'Accuracy':>10}")
print('='*58)
for name, acc in [
    ('Audio CNN (unimodal)',           audio_test_acc),
    ('Text RNN (unimodal)',            text_test_acc),
    ('Early Fusion',                   fusion_test_acc),
    ('Late Fusion - Average',          avg_acc),
    ('Late Fusion - Weighted (0.7/0.3)', weighted_acc),
    ('Late Fusion - Max confidence',   max_acc),
]:
    marker = ' ◀ BEST' if acc == max(audio_test_acc, text_test_acc,
                                      fusion_test_acc, avg_acc,
                                      weighted_acc, max_acc) else ''
    print(f'{name:<38} {acc:>10.4f}{marker}')
print('='*58)

combined_loss   = history_fusion_p1.history['loss']   + history_fusion_p2.history['loss']
combined_val    = history_fusion_p1.history['val_loss']+ history_fusion_p2.history['val_loss']
combined_hist   = type('H', (), {'history': {'loss': combined_loss, 'val_loss': combined_val}})()

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, hist, title in zip(axes,
    [history_audio, history_text, combined_hist],
    ['Audio CNN', 'Text RNN', 'Early Fusion (ph1+ph2)']):
    ax.plot(hist.history['loss'], label='Train loss')
    ax.plot(hist.history['val_loss'], label='Val loss')
    ax.set_title(title); ax.set_xlabel('Epoch'); ax.legend()
plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=120)
plt.show()

best_preds   = fusion_model.predict([X_a_test, X_t_test]).argmax(axis=1)
cm           = confusion_matrix(y_test, best_preds)
emotion_names = list(EMOTION_MAP.values())

plt.figure(figsize=(9, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=emotion_names, yticklabels=emotion_names)
plt.ylabel('True'); plt.xlabel('Predicted')
plt.title('Confusion Matrix — Early Fusion')
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=120)
plt.show()

print('\nClassification Report (Early Fusion):')
print(classification_report(y_test, best_preds, target_names=emotion_names))